### ISSUE TITLE
Gulp build extremly slow

### ISSUE THREAD

**Issue by happschinson** [flatlogic/angular-material-dashboard#10]
Hi!
When I start gulp build, the process takes up to 2 minutes until my project is built.
Is this a normal behaviour?

**Comment by bsitruk** [comment]
Hi,
Maybe cause you had an big minified library.
The build task might bug in some case.

**Comment by shoudaos** [comment]
this happens because of low perfomance of system what you use.

**Comment by happschinson** [comment]
problem "solved" with new gulp version.
gulp build time now around 30s

**Comment by happschinson** [comment]
i own a mac pro with 16gb ram, so I don't think it's a system problem..
