### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by bsitruk** [flatlogic/angular-material-dashboard#11]
Hi,
I worked a lot on a fork of this project recently.
I would eventually spend some time making some improvements on the dashboard layout.
Just wanted to know if anyone would be interested.

Let me know :)

**Comment by okendoken** [comment]
@bsitruk hey!
Of course! What exactly have you improved?

**Comment by bsitruk** [comment]
A first idea would be to associate a dedicated scrollbar to the dashboard,
and another one to the right sidebar.
I'll make a PR this WE.
