### ISSUE TITLE
warnings graph overlay error

### ISSUE THREAD

**Issue by matteocrippa** [flatlogic/angular-material-dashboard#13]
It seems that using at least safari if you go mouse over the warning graphs following the graph path the number is rendered in the upper left corner of the canvas and the it quickly move over the graph

**Comment by micrum** [comment]
Hi @matteocrippa , thanks for the report! 
Can't reproduce issue on my machine (OS X Yosemite 10.10.5, Safari Version 9.0).
Is issue still observed? Which Safari version you are using?

**Comment by matteocrippa** [comment]
I'm testing now on 10.11 and safari 9.0 and now works fine, 'll close this issue tho.
