### ISSUE TITLE
Left Nav Bar item spacing is way off

### ISSUE THREAD

**Issue by ggunders** [flatlogic/angular-material-dashboard#15]
cloned the repository and installed on Mac. Both chrome and Safari arent spacing the left nav items correctly. The three items are spaced hundreds of pixels apart.

**Comment by clarkmcnally** [comment]
I am seeing the same issue after cloning repo

**Comment by micrum** [comment]
@ggunders @clarkmcnally , thanks guys.
Will be fixed asap

**Comment by micrum** [comment]
Seems like custom styles from */src/app/stylesheets/* can't build on your machine. try to figure out with this problem

**Comment by shoudaos** [comment]
fixed. you may to install sass gem.
https://github.com/flatlogic/angular-material-dashboard/commit/b5b3bd6eaede5c6baa12f909c9a56c3e3dac2683

**Comment by ggunders** [comment]
didnt realize the build process failed on sass. installed and it works fine now. thanks. excellent starter app
