### ISSUE TITLE
Couldnt figure out the installation and testing

### ISSUE THREAD

**Issue by egemenertugrul** [flatlogic/angular-material-dashboard#16]
please make your explanations more clear so that a newb like me can understand the procedure. getting some errors such as 
Cannot find module 'multimatch'
when i try to "gulp serve",
even though i entered the commands and installed (i guess) the required things.

thanks in advance

**Comment by micrum** [comment]
Hi @egemenertugrul, could you please try to install Gulp globally?
    npm install --global gulp

**Comment by egemenertugrul** [comment]
Okay, here's what i've done, I ran all those commands (along with global installations) inside the \angular-material-dashboard-master folder (main) . In the end, two new folders were created bower_components, node_modules. What am i doing wrong?

**Comment by micrum** [comment]
All right, those new folders contains vendor libs. Is the problem still observed after installation?

**Comment by egemenertugrul** [comment]
Yes,it occurs

Error: Cannot find module 'multimatch'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\steril\Desktop\angular-material-dashboard-ma
ster\node_modules\gulp-load-plugins\index.js:2:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by micrum** [comment]
seems like something went wrong with the plugins installation.
Try to reinstall gulp dependencies:

    $ npm uninstall gulp-load-plugins
    $ npm install gulp-load-plugins

If this doesn't work try to remove entire node_modules folder and re-install modules.

    $ rm -rf node_modules
    $ npm install

**Comment by micrum** [comment]
I noticed that you are Windows user, so instead of `rm -f` command  use `rmdir`

**Comment by egemenertugrul** [comment]
Thanks for your help, a clean install figured it out.  I'm sorry for taking your time..

**Comment by micrum** [comment]
no problem, thanks for using our project
