### ISSUE TITLE
Profile menu doesn't disappear on message section click

### ISSUE THREAD

**Issue by micrum** [flatlogic/angular-material-dashboard#18]
Profile menu doesn't disappear on message section click.

1) Click to user name "Richard Feynman"
2) Click to any point of right sidebar

Actual result: profile menu doesn't disappears
Expected result: profile menu disappears (click to main content to see the difference)

Also, profile menu doesn't close when you re-click the button to open it

**Comment by kannach** [comment]
I have tested in firefox and chrome. The profile menu disappears. is it already fixed ?
