### ISSUE TITLE
UX issues

### ISSUE THREAD

**Issue by micrum** [flatlogic/angular-material-dashboard#20]
From the feedback on [Reddit thread](https://www.reddit.com/r/angularjs/comments/3ev39y/angular_material_dashboard_responsive_angular/):

- Click the top right hand button to show a bottom sheet? That makes no sense and feels really strange. Perhaps that button should close the right hand pane. A user of that site might not always need to see the messages, so giving them more screen real estate for content that matters would be much better.
Also, the menu directive that pops up when you click on the user's name is misplaced. It should be aligned to something, not just arbitrarily thrown in the mix. You can use the ng-offset directive to move it around to a better position.

- The 'Remove Completed' on the task list. It sits next to the plus Icon. It looks like the label for the plus icon. I was confused as to why a plus meant remove. They need to be more clearly two separate controls.

- Not being able to remove the messages list is annoying

- Clicking on the add task button adds an empty task that can't be edited. I had no feedback that I should enter text before clicking that button, and I shouldn't be able to click it when there is no text. The button and the text input should be better combined into a single control. And you should be able to edit the text of tasks.

**Comment by gaykov** [comment]
I propose this layout changes: http://gaykov.github.io/angular-material-dashboard/site/#/dashboard

@micrum give your feedback please

**Comment by micrum** [comment]
@gaykov looks good, especially TODO-list! Please, prepare PR
One comment: overlay and sidebar not covers all screen height upon scroll.

![screen shot 2015-11-23 at 3 28 06 pm](https://cloud.githubusercontent.com/assets/3502654/11336539/35ca1660-91f7-11e5-93e7-872b355c002d.png)

**Comment by Misiu** [comment]
@gaykov this look great.
I've noticed one more thing: when moving between pages  (for example from Dashboard to Profile) in bottom right corner we can see notification showing current page (md-toast). Unfortunately on pages without scroll-bar when notification is showing scroll-bar appear when notification is showing and hiding
This is visible on Profile page.
Could You fix this?

**Comment by gaykov** [comment]
@Misiu hello, thank you for your comment! But I can't reproduce this error. Could you please tell which browser do you use?

**Comment by Misiu** [comment]
I see on demo page that toast are showing in top right corner (this was recently changed). Now all scrollbars are showing correctly.
Thanks for fix :smile:
