### ISSUE TITLE
gulp ruby sass will not generate app css in windows platform

### ISSUE THREAD

**Issue by mamtou** [flatlogic/angular-material-dashboard#21]
gulp ruby sass will not generate app css in windows platform,
but when I replace gulp-ruby-sass to gulp-sass It's OK

**Comment by micrum** [comment]
thanks for comment @mantouxu !
Have you tried to install Ruby or Sass before replacing gulp lib?

**Comment by mantouxu** [comment]
Yes, I have installed Ruby and Sass But "app.css" not replaced and the .tmp folder is not have it.

**Comment by marszczybrew** [comment]
Had the same issue here when using Windows' cmd. It worked when I launched it with babun though

**Comment by shanemgrey** [comment]
Is ruby-sass needed?  Or will node-sass do ok?  I prefer to not have the extra ruby dep to deal with, and libsass is much faster to compile.

**Comment by sminodonte** [comment]
Had the same issue, not not generate app css in windows
