### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ekarlso** [flatlogic/angular-material-dashboard#27]
I'm doing "npm install" and it always stops, any ideas on this?
loadDep:path-is-absolute

**Comment by micrum** [comment]
@ekarlso Could you please provide more detailed errors log

**Comment by micrum** [comment]
@ekarlso In which directory you run command?

**Comment by ekarlso** [comment]
In the root of the repo.

2015-12-18 14:19 GMT+01:00 Michael Rumiancaŭ <notifications@github.com>:

**Comment by ekarlso** [comment]
Turns out it was a computer issue..
