### ISSUE TITLE
Will there be any es6 support?

### ISSUE THREAD

**Issue by ekarlso** [flatlogic/angular-material-dashboard#28]
See q

**Comment by okendoken** [comment]
@ekarlso I think yes, we are going to spend some time soon creating Angular 2.0 branch.
@micrum what are your ideas on this?

**Comment by ekarlso** [comment]
What would you recommend for making a dashboard at this time?

Endre Karlson
19. des. 2015 8.53 a.m. skrev "Philip Daineka" <notifications@github.com>:

**Comment by micrum** [comment]
yep, we really plan to support ES6.
@ekarlso at this time I can recommend to try https://github.com/Excelian/Angular-Material-ECMA6-Dashboard

**Comment by gotnull** [comment]
@micrum That's hideous.
