### ISSUE TITLE
views/partials/memory.html Firefox fix

### ISSUE THREAD

**Issue by rubenmendoza** [flatlogic/angular-material-dashboard#30]
`<md-content ng-controller="MemoryController as vm" class="md-padding" layout="row" layout-align="center center">
   <div flex>
    <nvd3 options="vm.chartOptions" data="vm.memoryChartData"></nvd3>
    </div>
</md-content>`

**Comment by rubenmendoza** [comment]
Looks like `<div flex>` must enclose `<nvd3>` tags

**Comment by micrum** [comment]
Hi @rubenmendoza !
Do you observed some issues with D3 in Firefox? If so, could you please provide PR?

**Comment by gaykov** [comment]
I tested it in latest Firefox versions, seems like it works good. Closing this issue. Please reopen if it still happens to you.
