### ISSUE TITLE
Dashboard is working only partially on FireFox

### ISSUE THREAD

**Issue by eliktz** [flatlogic/angular-material-dashboard#37]
some of the panels show blank

**Comment by mautematico** [comment]
Are you able to upload screenshots about this?
It would be also helpful if you can post details of your Firefox (like build number and complete User Agent string).

:D

**Comment by micrum** [comment]
thanks @mautematico :)
@eliktz could you please clarify your problem?

**Comment by eliktz** [comment]
@mautematico @micrum Thanks for your replies, after further investigation turned out there was something incoherent with how i set up the html.
Thanks anyway and keep up the good work

**Comment by micrum** [comment]
@eliktz thanks for using AMD, closing the issue
