### ISSUE TITLE
Issue with Gulp serve

### ISSUE THREAD

**Issue by prasadyallapu** [flatlogic/angular-material-dashboard#38]
When i am giving "gulp serve" .There is a error that cant find module "Cannot find module 'gulp-protracto" .So please help me out new to Nodejs.

**Comment by pensado** [comment]
Just install missing modules using npm.
Ex.: `sudo npm install gulp-protracto -g`

**Comment by micrum** [comment]
Hi @prasadyallapu
Please go to **angular-material-dashboard** directory and install node modules by command:

    $ npm install

**Comment by prasadyallapu** [comment]
Still the same issue @pensado  and @micrum

**Comment by micrum** [comment]
@prasadyallapu could you please provide logs?

**Comment by barneydmedia** [comment]
I had a similar issue installing this tonight, but I resolved it by deleting my node_modules folder and doing another `npm install`. I think I encountered a partial install error with npm, and that caused the dependency failures.

**Comment by Duansoft** [comment]
Thanks for your help
