### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by ctwoodwa** [flatlogic/angular-material-dashboard#40]
The demo page viewed from internet explorer 11.
![angularmaterialdashboardonie](https://cloud.githubusercontent.com/assets/1328090/12859364/a8a8159a-cc23-11e5-9d4b-a8353ca4dbbc.png)

**Comment by micrum** [comment]
thanks for the report, @ctwoodwa !
confirmed

**Comment by DimaSavchenko** [comment]
All right for me.![image](https://cloud.githubusercontent.com/assets/11638499/23404986/f0c514ae-fdc8-11e6-9be6-958de319b913.png)
