### ISSUE TITLE
Unable to run angular js admin templates.

### ISSUE THREAD

**Issue by singhkgp** [flatlogic/angular-material-dashboard#41]
tell me about steps to run angular js admin templates.

I have download .zip file (https://codeload.github.com/flatlogic/angular-material-dashboard/zip/master) and extract it on desktop.

when I want to open index.html file in chrome browser, It is not open.

What should I do for run it properly.

**Comment by micrum** [comment]
@singhkgp you can run project the same way as by cloning from git. Please see [Readme ](https://github.com/flatlogic/angular-material-dashboard#getting-started).

If you need static project - run `gulp build ` instead of `gulp serve`
