### ISSUE TITLE
Pagination on table view

### ISSUE THREAD

**Issue by tigrus** [flatlogic/angular-material-dashboard#42]
It's cool to have pagination on table view as example.

**Comment by micrum** [comment]
Hi @tigrus thanks for the feedback. Table component is still unimplemented in Angular Material. I think no sense to handle pagination untill https://github.com/angular/material/issues/796 is open

**Comment by tigrus** [comment]
@micrum ok :+1:

**Comment by torabian** [comment]
I have added Pagination table and sent a pull request. You may check.
