### ISSUE TITLE
use libsass instead gem sass

### ISSUE THREAD

**Issue by darlanmendonca** [flatlogic/angular-material-dashboard#54]
Hello, I begin look for your project, and I appreciate it, congratulations for the project.

One suggestion for performance, is use libsass (npm module) instead gem sass.

Libsass can compile in average 1/10 time from gem sass.

If you wish, I can make a PR, to show it's better

**Comment by DimaSavchenko** [comment]
Hi, @darlanmendonca! Thanks for your proposal. PR is cool!
