### ISSUE TITLE
bower error during npm install

### ISSUE THREAD

**Issue by chegie** [flatlogic/angular-material-dashboard#57]
please, i got this error during npm install. How do i go about it? Thank you.
--------
pm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-material-dashboard@1.3.0 install: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-material-dashboard@1.3.0 install script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-material-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-material-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-material-dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by chegie** [comment]
I just got it.

I installed bower components by executing 
$ bower install

then i ran the npm
$ npm install

**Comment by mastermindg** [comment]
Why not add bower in package.json?
