### ISSUE TITLE
Browers support

### ISSUE THREAD

**Issue by bsitruk** [flatlogic/angular-material-dashboard#6]
Chrome: The messages side bar is lagging on scroll, and only scroll until the next sticky element.
Mozilla: Charts missing + layout broken on the right sidebar...

Same for you ?

**Comment by bsitruk** [comment]
I will try to correct these

**Comment by micrum** [comment]
thanks for comments @bsitruk !
feel free to provide adjustments in PR

**Comment by micrum** [comment]
Messages sidebar performance issue resolved by downgrading angular #7

**Comment by bsitruk** [comment]
I did a fork, so you can look at my changes and take what you want.
I'm currently just working on the layout.
