### ISSUE TITLE
getting "ERR! registry error parsing json" when running npm install on the root folder 

### ISSUE THREAD

**Issue by nadavbi2310** [flatlogic/angular-material-dashboard#65]
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <HEAD><TITLE>Proxy Authorization Required</TITLE></HEAD>
npm ERR! <BODY BGCOLOR="white" FGCOLOR="black"><H1>Proxy Authorization Required<
/H1><HR>
npm ERR! <FONT FACE="Helvetica,Arial"><B>
npm ERR! Description: Authorization is required for access to this proxy<BR><BR>

npm ERR! </B>Error Code: <BR>ER (null)<BR><BR>
npm ERR! User Agent: <BR>npm/4.1.2 node/v7.5.0 win32 x64<BR><BR>
npm ERR! Error Detail: <BR><PRE>NT_STATUS_WRONG_PASSWORD: Wrong Password (0xc000
006a)
npm ERR! </PRE><BR><BR></B></FONT>
npm ERR! <HR>
npm ERR! 
npm ERR! </BODY>
npm ERR!

npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\nadavbi\Documents\visual studio code\projects\angular-mate
rial-dashboard-master\npm-debug.log

**Comment by DimaSavchenko** [comment]
Hi @nadavbi2310 !
Try something like that:
**sudo npm install npm -g**
**rm -rf node_modules and npm cache clean and npm config set registry "http://registry.npmjs.org/"**
