### ISSUE TITLE
"bower install" failed when extracting bower-angular-cookie

### ISSUE THREAD

**Issue by jianwu-github** [flatlogic/angular-material-dashboard#8]
> angular-material-admin@1.0.1 install /Users/jianwu/angularjs/gitrepos/angular-material-dashboard-1
> bower install

bower angular-animate#~1.3.4    cached git://github.com/angular/bower-angular-animate.git#1.3.8
bower angular-animate#~1.3.4  validate 1.3.8 against git://github.com/angular/bower-angular-animate.git#~1.3.4
bower angular-cookies#~1.3.4    cached git://github.com/angular/bower-angular-cookies.git#1.3.8
bower angular-cookies#~1.3.4  validate 1.3.8 against git://github.com/angular/bower-angular-cookies.git#~1.3.4
bower angular-sanitize#~1.3.4   cached git://github.com/angular/bower-angular-sanitize.git#1.3.8
bower angular-sanitize#~1.3.4 validate 1.3.8 against git://github.com/angular/bower-angular-sanitize.git#~1.3.4
bower jquery#~2.1.1             cached git://github.com/jquery/jquery.git#2.1.4
bower jquery#~2.1.1           validate 2.1.4 against git://github.com/jquery/jquery.git#~2.1.1
bower angular-touch#~1.3.4      cached git://github.com/angular/bower-angular-touch.git#1.3.8
bower angular-touch#~1.3.4    validate 1.3.8 against git://github.com/angular/bower-angular-touch.git#~1.3.4
bower angular#1.3.15            cached git://github.com/angular/bower-angular.git#1.3.15
bower angular#1.3.15          validate 1.3.15 against git://github.com/angular/bower-angular.git#1.3.15
bower angular-ui-router#~0.2.13 cached git://github.com/angular-ui/ui-router.git#0.2.15
bower angular-ui-router#~0.2.13         validate 0.2.15 against git://github.com/angular-ui/ui-router.git#~0.2.13
bower angular-material#~0.10.0            cached git://github.com/angular/bower-material.git#0.10.0
bower angular-material#~0.10.0          validate 0.10.0 against git://github.com/angular/bower-material.git#~0.10.0
bower angular-mocks#~1.3.4                cached git://github.com/angular/bower-angular-mocks.git#1.3.17
bower angular-mocks#~1.3.4              validate 1.3.17 against git://github.com/angular/bower-angular-mocks.git#~1.3.4
bower angular-nvd3#1.0.0-rc.2             cached git://github.com/krispo/angular-nvd3.git#1.0.0-rc.2
bower angular-nvd3#1.0.0-rc.2           validate 1.0.0-rc.2 against git://github.com/krispo/angular-nvd3.git#1.0.0-rc.2
bower angular-sanitize#~1.3.4                new version for git://github.com/angular/bower-angular-sanitize.git#~1.3.4
bower angular-sanitize#~1.3.4            resolve git://github.com/angular/bower-angular-sanitize.git#~1.3.4
bower angular-touch#~1.3.4                   new version for git://github.com/angular/bower-angular-touch.git#~1.3.4
bower angular-touch#~1.3.4               resolve git://github.com/angular/bower-angular-touch.git#~1.3.4
bower angular-animate#~1.3.4                 new version for git://github.com/angular/bower-angular-animate.git#~1.3.4
bower angular-animate#~1.3.4             resolve git://github.com/angular/bower-angular-animate.git#~1.3.4
bower angular-cookies#~1.3.4                 new version for git://github.com/angular/bower-angular-cookies.git#~1.3.4
bower angular-cookies#~1.3.4             resolve git://github.com/angular/bower-angular-cookies.git#~1.3.4
bower angular-sanitize#~1.3.4           download https://github.com/angular/bower-angular-sanitize/archive/v1.3.17.tar.gz
bower angular-touch#~1.3.4              download https://github.com/angular/bower-angular-touch/archive/v1.3.17.tar.gz
bower angular-animate#~1.3.4            download https://github.com/angular/bower-angular-animate/archive/v1.3.17.tar.gz
bower angular-cookies#~1.3.4            download https://github.com/angular/bower-angular-cookies/archive/v1.3.17.tar.gz
bower angular-animate#^1.3.0 || >1.4.0-beta.0           cached git://github.com/angular/bower-angular-animate.git#1.3.8
bower angular-animate#^1.3.0 || >1.4.0-beta.0         validate 1.3.8 against git://github.com/angular/bower-angular-animate.git#^1.3.0 || >1.4.0-beta.0
bower angular-animate#^1.3.0 || >1.4.0-beta.0              new version for git://github.com/angular/bower-angular-animate.git#^1.3.0 || >1.4.0-beta.0
bower angular-animate#^1.3.0 || >1.4.0-beta.0          resolve git://github.com/angular/bower-angular-animate.git#^1.3.0 || >1.4.0-beta.0
bower nvd3#^1.7.1                                   not-cached git://github.com/novus/nvd3.git#^1.7.1
bower nvd3#^1.7.1                                      resolve git://github.com/novus/nvd3.git#^1.7.1
bower d3#^3.3.13                                        cached git://github.com/mbostock/d3.git#3.3.13
bower d3#^3.3.13                                      validate 3.3.13 against git://github.com/mbostock/d3.git#^3.3.13
bower angular-animate#^1.3.0 || >1.4.0-beta.0         download https://github.com/angular/bower-angular-animate/archive/v1.4.3.tar.gz
bower angular#1.3.17                                    cached git://github.com/angular/bower-angular.git#1.3.17
bower angular#1.3.17                                  validate 1.3.17 against git://github.com/angular/bower-angular.git#1.3.17
bower angular-aria#^1.3.15 || >1.4.0-beta.0             cached git://github.com/angular/bower-angular-aria.git#1.4.3
bower angular-aria#^1.3.15 || >1.4.0-beta.0           validate 1.4.3 against git://github.com/angular/bower-angular-aria.git#^1.3.15 || >1.4.0-beta.0
bower nvd3#^1.7.1                                     download https://github.com/novus/nvd3/archive/v1.8.1.tar.gz
bower angular-cookies#~1.3.4                           extract archive.tar.gz
bower angular-touch#~1.3.4                             extract archive.tar.gz
bower angular-sanitize#~1.3.4                          extract archive.tar.gz
bower d3#^3.3.13                                           new version for git://github.com/mbostock/d3.git#^3.3.13
bower d3#^3.3.13                                       resolve git://github.com/mbostock/d3.git#^3.3.13
bower d3#^3.3.13                                      download https://github.com/mbostock/d3/archive/v3.5.6.tar.gz
bower angular-animate#~1.3.4                           extract archive.tar.gz
bower angular-animate#^1.3.0 || >1.4.0-beta.0          extract archive.tar.gz
bower nvd3#^1.7.1                                      extract archive.tar.gz
bower d3#^3.3.13                                       extract archive.tar.gz
bower angular-cookies#~1.3.4                            EACCES EACCES, rename '/var/folders/z7/zt2wlkbj59z3k0vxs3f9182r0000gn/T/jianwu/bower/angular-cookies-5547-2SR0eD'

Stack trace:
Error: EACCES, rename '/var/folders/z7/zt2wlkbj59z3k0vxs3f9182r0000gn/T/jianwu/bower/angular-cookies-5547-2SR0eD'

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.10.28
OS: Darwin 14.0.0 x64

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.28
npm ERR! npm  v2.13.4
npm ERR! code ELIFECYCLE
npm ERR! angular-material-admin@1.0.1 install: `bower install`
npm ERR! Exit status 1

**Comment by okendoken** [comment]
@jianwu-github seems like a problem with your environment/setup.
Just tried to do the same on Windows - everything worked well

@micrum ideas?

**Comment by micrum** [comment]
@jianwu-github installation failed due to permissions problem on your machine.
Anyway, you don't need to call 'bower install' comand, as this command added as post-script to 'npm install'.
To install dependencies just call 'npm install'

**Comment by jianwu-github** [comment]
I was building it on Mac OS X, and "bower install" was called from "npm install", I just copied log output from "bower install" to the point of failure as the full log would be too long

**Comment by jianwu-github** [comment]
Would it be possible to create a "distributed" or "released" edition including all the dependencies?

I would argue that either "bower" or "npm" is not robust build-tool if you compare with ant, maven, and gradle and it is hard for new people to debug once these tools failed in certain environment.

**Comment by okendoken** [comment]
@jianwu-github maybe you want to try the same command with `sudo` ?

**Comment by micrum** [comment]
@jianwu-github please have a look at similar problem on [http://stackoverflow.com/questions/22257726/eacces-error-with-bower-install](stackoverflow)

**Comment by jianwu-github** [comment]
@okendoken I tried and bower gave me warning saying I should not use sudo to do "bower install" as it is a local install, which is different from "npm" install globally.

@micum Thanks for the info! I'll take a look
