### ISSUE TITLE
gulp-ruby-sass stderr

### ISSUE THREAD

**Issue by happschinson** [flatlogic/angular-material-dashboard#9]
Hi,

when I try to run gulp serve, i get the following error:
gulp-ruby-sass stderr 

can you help me? :)

**Comment by micrum** [comment]
Hi @happschinson,
Could you please provide more details?

**Comment by happschinson** [comment]
I had an outdated sass version. Updated to the latest - running fine now!

**Comment by micrum** [comment]
@happschinson cool! :)
I close the issue.
